### ISSUE TITLE
Is there a full working example with the latest Angular?

### ISSUE THREAD

**Issue by kamal2311** [jinhduong/ng2-awesomplete#1]
I tried in my project and ended up getting this error

`ERROR in Error: AwesompleteModule is not an NgModule`

In my module where I import AwesompleteModule, this statement is there at the top
`import { AwesompleteModule } from 'ng2-awesomplete/auto-complete.module';`

**Comment by jinhduong** [comment]
Yes it's full working with latest version.
You have to import like as:
``` js
import { AwesompleteModule } from 'ng2-awesomplete'
```
